### ISSUE TITLE
회원가입

### ISSUE THREAD

**Issue by kisstest** [gumpcha/good-reads-clone#16]
> 회원가입 후 일정시간이 지난 후 같은 이메일과 패스워드로 로그인 시도시 유효하지 않은 정보라며 에러 표시

**Comment by gumpcha** [comment]
free tier로 배포한 heroku app은 마지막 request 이후로 30분 정도면 자동으로 내려갑니다. - https://devcenter.heroku.com/articles/free-dyno-hours#dyno-sleeping

user 정보를 db 말고 memory에만 저장해 두었으니, sleeping 된 후 다시 접속할 경우 memory가 날라가서 가입 정보가 없어지는 것 같네요.

맞는지 확인을 위해 로그인 에러날 경우의 api 응답을 긁어서 보여주세요.

이 이슈와 별개로 db layer를 빨리 추가하도록 하겠습니다. 😅 

<blockquote><img src="https://www.herokucdn.com/favicons/favicon.ico" width="48" align="right"><div><strong><a href="https://devcenter.heroku.com/articles/free-dyno-hours#dyno-sleeping">Free Dyno Hours | Heroku Dev Center</a></strong></div><div>Every personal Heroku account is allocated a pool of hours which you can use with Free dynos. This article describes the behavior of apps using Free dynos.</div></blockquote>

**Comment by kisstest** [comment]
넵~

**Comment by kisstest** [comment]
로그인에 대한 응답결과입니다
은근히 좀 바빠서 늦었네요 ^^;
```
request 
url:  https://good-reads-clone-api-express.herokuapp.com/user/session
method: POST
payload: {
  email: "kisstest2@gmail.com"
  password: "!1234qwer"
}


response
code: 401
message: "email/password mismatch(0)"
```

**Comment by gumpcha** [comment]
맞네요. 서버가 idle -> active 되면서 회원 정보가 날라갔어요. db 작업 중이니, 끝나면 알려드릴게요.

**Comment by kisstest** [comment]
서버쪽은 완전 문외한이라 ㅜㅜ
서버 이해를 돕기위한 블로그나 책같은거 추천하실만한거 있으세요?
대략 포괄적인 것으로다가 ㅎㅎ

**Comment by gumpcha** [comment]
실제로 해 보는게 좋을거 같아요.

1. node 설치
1. https://expressjs.com/ko/starter/hello-world.html 실행
1. 브라우져에서 localhost:3000 으로 접속해 보기

위 내용 성공하면 http method(get/post/delete/put) + endpoint(/users, /books) 추가하는거 같이 진행해 보시죠.

<blockquote><img src="https://expressjs.com/images/express-facebook-share.png" width="48" align="right"><div><strong><a href="https://expressjs.com/ko/starter/hello-world.html">Express "Hello World" 예제</a></strong></div></blockquote>

**Comment by kisstest** [comment]
넵 감솨합니다^^

**Comment by gumpcha** [comment]
#28 에서 수정됨
